### ISSUE TITLE
ClickOnceUninstaller

### ISSUE THREAD

**Issue by Aphetoros** [6wunderkinder/Wunder.ClickOnceUninstaller#8]
Hi,

I'm kind of new here. How would I get this to work? Is there a step-by-step instructions somewhere for me to get this going? I use PDQ Deploy and would love to use this together.

Thank you very much,
 Aphetoros

**Comment by christianlang** [comment]
Hi Aphetoros,

there are several ways to use this: from .NET, from the command-line, and directly from a MSI package. You should find everything you need in the [README file](https://github.com/6wunderkinder/Wunder.ClickOnceUninstaller/blob/master/README.md). 

Chris

**Comment by Aphetoros** [comment]
Hi Chris,

For the command-line, where would I find "ClickOnceUninstaller.exe" from? I apologize if this is a stupid question.

-Aphetoros

**Comment by christianlang** [comment]
You will need to get the source code (either clone the repository in git or download as [zip file](https://github.com/6wunderkinder/Wunder.ClickOnceUninstaller/archive/master.zip)). Then open it in Visual Studio and build it. This will create the .exe file you need, somewhere in a "bin" subfolder. 

Chris

**Comment by Aphetoros** [comment]
Awesome Chris. Thank you :)

Is there a way to uninstall a _specific_ version of an application?

**Comment by christianlang** [comment]
No, unfortunately not. The goal of this tool was to remove the ClickOnce installation completely if you want to switch to a different installer.

**Comment by Aphetoros** [comment]
Thank you Chris! Great tool!

**Comment by atchutachanta** [comment]
will this work on windows 10 ?
